### ISSUE TITLE
Add-on to issue #9

### ISSUE THREAD

**Issue by rxkt** [k0np4ku/Azur-Lane-Scripts-Autopatcher#14]
All of my recompiled scripts were of the same size so I checked the files.

I did not get a prompt from luajit.exe until I messed with its DLL file (cyglua51.dll -> lua51.dll)
Then said I was missing cygwin1.dll, so installation of cygwin + updating PATH with its /bin/ folder is necessary as well. 

It could be nice if you include a renamed copy for those who are using CMD and not cygwin as well. Not sure if installing cygwin will let me use cyglua51.dll still.

**Comment by rxkt** [comment]
Actually, just installed cygwin and still having the same issue lol
Python+.NET installed with proper PATH vars as well, but I'll try to mess with it a bit more

**Comment by k0np4ku** [comment]
Luajit is not the problem here, I can assure this because I've tested the tool on a fresh installed W7 x86 inside VirtualBox with only .NET Framework 4.5.1 and Python 3 Installed, including imported Python to Path Environment Variables.

There's a possibility that Rewriter.exe isn't compatible with your Operating System, or the LUAs weren't decompiled at all. 

1. Try compile Rewriter.exe on your own by downloading this tool's source code and [Golang](https://golang.org/), then run `go build` command inside Rewriter directory.
2. Try enabling GenerateDebugZip and re-run the tool, then you will get Debug.Zip. You will also get Logs.txt if something went wrong. (Please upload both file if you get any)

**Comment by rxkt** [comment]
Compiled Rewriter.exe and I noticed a new window pop-up that I haven't seen before (when using CMD). When using cygwin the rewrite step is noticeably longer (probably because it was running properly now).

However all files are still the same size, and no debug logs were created.

Maybe all files need to be recompiled from scratch?

**Comment by k0np4ku** [comment]
Do you get debug.zip?

**Comment by rxkt** [comment]
Yeah I have it.  Lua.txt's don't look decrypted so I recompiled Azcli. Everything still has same file size and the files in debug are still encrypted.

**Comment by k0np4ku** [comment]
Please upload debug.zip here.

**Comment by rxkt** [comment]
[Debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2252401/Debug.zip)

**Comment by k0np4ku** [comment]
I've checked your Debug.zip and it seems all lua succesfully decrypted but not decompiled, which means the problem is either the decompiler (Ljd) or your python.

As what I already stated in https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/issues/9#issuecomment-406273704, add python directory to System Environment Variables named **Path** and check whether python is working as intended by running `python --version` command.

**Comment by rxkt** [comment]
python --version returns 3.5.2, and python is already in my PATH env var.

**Comment by rxkt** [comment]
I ran main.py and an error pops up on line 156, is this an issue?
![image](https://user-images.githubusercontent.com/7422875/43567557-13e5f7c0-9600-11e8-85c1-bb66427ba555.png)

**Comment by k0np4ku** [comment]
Try install newer version of python (3.7.0), same thing happened when I'm using 3.5.2 and things fixed when I'm using 3.7.0

**Comment by rxkt** [comment]
Oh it's an F string literal, I see. I removed the f in the literal and it worked using 3.5.2, all files have different sizes.

**Comment by rxkt** [comment]
Going to try using the original release folder and fixing the main.py first to see if I needed to recompile the other .exe's

**Comment by rxkt** [comment]
Updated to 3.7 with python --version and path stuff fixed, back to being bugged w/ same size files

**Comment by rxkt** [comment]
Looks like the clean release worked after I updated python! Was really confusing because of the "3.0+ python req" so I thought that python was really not the issue with 3.5.2. Thanks for the help!

**Comment by k0np4ku** [comment]
Yeah, that's my fault because I thought any python version is fine as long it's 3.0 and above. I'll edit the requirements and make it more clear so this issue won't happens to someone else. Thanks as well.
