### ISSUE TITLE
A little suggestion about the revision

### ISSUE THREAD

**Issue by 1354961639** [k0np4ku/Azur-Lane-Scripts-Autopatcher#5]
First of all, thank you for such a tool as open source

But I have some suggestions in the process of using it to give you.

1. can you modify a device to achieve a team with modification effect and no modification effect (so that it can be used for ranking).

2. can you modify the default skin for other skin

**Comment by k0np4ku** [comment]
1. I have no plan to add or change an existing feature because everything is fine and working so far, and I intentionally not providing a generated scripts that will gives the player an advantage in PvP, because ranking should always be avoided when you're not a legit player.

2. There was, but I decided to revert the changes because this feature was abused by scammers to sell their account and claims that their account is full of paid skins, when in fact, they're fake. If you have some programming or Visual Studio experience, you can implement it by yourself, but please, don't use it to gain profit: https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/commit/69bf3d700f577e6ae3889e0cf914f5d176fe5772
