### ISSUE TITLE
tool is working fine, but .......

### ISSUE THREAD

**Issue by uvdpqfa** [k0np4ku/Azur-Lane-Scripts-Autopatcher#9]
the game can run, but modify doesnt work
and the 8 modify scripts size are same

here is Debug.zip
[Debug.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2206827/Debug.zip)

my JPver original script
[JPver_scripts.zip](https://github.com/k0np4ku/Azur-Lane-Scripts-Autopatcher/files/2206885/JPver_scripts.zip)

**Comment by k0np4ku** [comment]
Which means Rewriter.exe is not working properly, what's your OS? 32-bit or 64-bit?

Try run a test by creating a folder named scripts-godmode-damage-cooldown inside temp folder and extract the first weapon_property.lua.txt, enemy_data_statistics.lua.txt, enemy_data_skill.lua.txt and aircraft_template.lua.txt into scripts-godmode-damage cooldown and run Rewriter.exe

After Rewriter.exe is finished doing its job, try open weapon_property.lua.txt and check whether all damage is 300

**Comment by uvdpqfa** [comment]
my OS is win7 64-bit

i tried and check the weapon_property.lua.txt just have damage words, can't find 300

**Comment by k0np4ku** [comment]
@uvdpqfa My bad, after I checked your debug.zip once again, it seems the lua files weren't even decompiled, which means for some reason the decompiler (Ljd) wasn't executed.

Make sure you have installed these system requirements:
- NET Framework 4.5.1 or newer https://www.microsoft.com/en-us/download/details.aspx?id=40779
- Python 3.0 or newer https://www.python.org/ftp/python/3.7.0/python-3.7.0.exe

**Comment by uvdpqfa** [comment]
I have installed these.
If I upgrade to win10 ,then will be normal ?

![net](https://user-images.githubusercontent.com/41179762/42929783-a95f3c0a-8b6d-11e8-80a3-20612c3854ec.png)
![python](https://user-images.githubusercontent.com/41179762/42929786-ac615c26-8b6d-11e8-96e1-ed6e5aaff593.png)

**Comment by k0np4ku** [comment]
I'm using Windows 7 x64 so there's no problem with your Operating System version.

## Solutin 1:
1. Try changing your System Locale to "English (United States)"

## Solution 2:
1. Check whether python is working as intended by running `python --version` inside cmd
2. A python that is working as intended will print your python version inside cmd, otherwise will print "Python is not a recognized as an internal or external command, operable program or batch file.", which means python is not working as intended due to python is not in your System Environment Variables.

### How to add python to System Environment Variables.
1. Navigate to `Control Panel > System > Advanced system settings > Advanced > Environment Variables`
2. Inside System variables section (bottom), search for a variable named **Path** and edit it, then add your python installation folder

https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows

If you don't find any python's installation folder inside program files, then it most likely located inside %LocalAppData%

Instead of reinstalling your Operating System to windows 10, you can try installing windows 7 x86 inside VirtualBox

**Comment by uvdpqfa** [comment]
OMG!!! its WORK!!!!!!!

I found my scripts-godmode-cooldown(JP) file size is different with yours, is that will be a problem ?
And I turn Replace_Skin to True, but I don't see anything change.


Thank you for solve my stupid problem.
I appreciated your time and effort.

**Comment by k0np4ku** [comment]
>I found my scripts-godmode-cooldown(JP) file size is different with yours, is that will be a problem ?

You won't know until you test it, but there won't be any problem unless you get Logs.txt

> And I turn Replace_Skin to True, but I don't see anything change.

Seems I forget to remove those, you can ignore it.
and you're welcome.
